### Récupérer toutes les structures
GET http://localhost:3000/api/companies
Content-Type: application/json

### Récupérer une structure
GET http://localhost:3000/api/company/1
Content-Type: application/json

### Ajout d'une structure
POST http://localhost:3000/api/companies
Content-Type: application/json

{
        "name": "association NPM",
        "structure": "Association",
        "department": 17
}

###
PATCH http://localhost:3000/api/company/1
Content-Type: application/json

{
    "name" : "entreprise_update"
}

### Suppression d'une structure
DELETE http://localhost:3000/api/company/3

### Récupérer toutes les site web de référence
GET http://localhost:3000/api/websites
Content-Type: application/json

### Ajout d'un nouveau site de référence
POST http://localhost:3000/api/websites
Content-Type: application/json

{
    "name":"RegionsJob"
}

### Suppression d'un site de référence
DELETE http://localhost:3000/api/website/1
Content-Type: application/json

### Récupération d'un site
GET http://localhost:3000/api/website/1
Content-Type: application/json

### Modification d'un site
PATCH http://localhost:3000/api/website/4
Content-Type: application/json

{
    "name" : "RegionsJob Rhône-Alpes"
}
### Récupérer toutes les offres d'emploi postulées
GET http://localhost:3000/api/offers
Content-Type: application/json

### Ajout d'une nouvelle offre d'emploi
POST http://localhost:3000/api/offers
Content-Type: application/json

{
    "employment" : "Développeur Full-Stack",
    "notes" : "Prise de contact sur Slack",
    "contact" : "Mr Handler",
    "offer_url" : "www.company.com/jobs/01",
    "website_id" : 1,
    "company_id" : 1
}

### Suppression d'une offre
DELETE http://localhost:3000/api/offer/3
Content-Type: application/json

### Selection d'une offre
GET http://localhost:3000/api/offer/1
Content-Type: application/json

### Modification d'une offre
PATCH http://localhost:3000/api/offer/1
Content-Type: application/json

{
    "contact" : "Mr Benetto",
    "employment" : "Développeur DevOps"
}

### Vue d'ensemble
GET http://localhost:3000/api/global