GET http://localhost:3000/api/companies
Content-Type: application/json
###

GET http://localhost:3000/api/company/1
Content-Type: application/json
###
GET http://localhost:3000/api/websites
Content-Type: application/json
###

POST http://localhost:3000/api/websites
Content-Type: application/json

{

    "name":"RegionsJob"
    
}

###
DELETE http://localhost:3000/api/website/3
Content-Type: application/json
###
GET http://localhost:3000/api/websites
Content-Type: application/json
###
GET http://localhost:3000/api/offers
Content-Type: application/json
###

GET http://localhost:3000/api/offer/1
Content-Type: application/json
###